name: Build RANI APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jdk zip unzip
          pip install cython==0.29.33 buildozer

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.buildozer
          key: bz-${{ hashFiles('buildozer.spec') }}

      - name: Build
        run: buildozer android debug

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: RANI-APK
          path: bin/*.apk
